def class_return():
    classes = [
        "The_Eiffel_Tower",
        "The_Great_Wall_of_China",
        "The_Mona_Lisa",
        "airplane",
        "alarm_clock",
        "ambulance",
        "angel",
        "animal_migration",
        "ant",
        "anvil",
        "apple",
        "arm",
        "asparagus",
        "axe",
        "backpack",
        "banana",
        "bandage",
        "barn",
        "baseball",
        "baseball_bat",
        "basket",
        "basketball",
        "bat",
        "bathtub",
        "beach",
        "bear",
        "beard",
        "bed",
        "bee",
        "belt",
        "bench",
        "bicycle",
        "binoculars",
        "bird",
        "birthday_cake",
        "blackberry",
        "blueberry",
        "book",
        "boomerang",
        "bottlecap",
        "bowtie",
        "bracelet",
        "brain",
        "bread",
        "bridge",
        "broccoli",
        "broom",
        "bucket",
        "bulldozer",
        "bus",
        "bush",
        "butterfly",
        "cactus",
        "cake",
        "calculator",
        "calendar",
        "camel",
        "camera",
        "camouflage",
        "campfire",
        "candle",
        "cannon",
        "canoe",
        "car",
        "carrot",
        "castle",
        "cat",
        "ceiling_fan",
        "cell_phone",
        "cello",
        "chair",
        "chandelier",
        "church",
        "circle",
        "clarinet",
        "clock",
        "cloud",
        "coffee_cup",
        "compass",
        "computer",
        "cookie",
        "cooler",
        "couch",
        "cow",
        "crab",
        "crayon",
        "crocodile",
        "crown",
        "cruise_ship",
        "cup",
        "diamond",
        "dishwasher",
        "diving_board",
        "dog",
        "dolphin",
        "donut",
        "door",
        "dragon",
        "dresser",
        "drill",
        "drums",
        "duck",
        "dumbbell",
        "ear",
        "elbow",
        "elephant",
        "envelope",
        "eraser",
        "eye",
        "eyeglasses",
        "face",
        "fan",
        "feather",
        "fence",
        "finger",
        "fire_hydrant",
        "fireplace",
        "firetruck",
        "fish",
        "flamingo",
        "flashlight",
        "flip_flops",
        "floor_lamp",
        "flower",
        "flying_saucer",
        "foot",
        "fork",
        "frog",
        "frying_pan",
        "garden",
        "garden_hose",
        "giraffe",
        "goatee",
        "golf_club",
        "grapes",
        "grass",
        "guitar",
        "hamburger",
        "hammer",
        "hand",
        "harp",
        "hat",
        "headphones",
        "hedgehog",
        "helicopter",
        "helmet",
        "hexagon",
        "hockey_puck",
        "hockey_stick",
        "horse",
        "hospital",
        "hot_air_balloon",
        "hot_dog",
        "hot_tub",
        "hourglass",
        "house",
        "house_plant",
        "hurricane",
        "ice_cream",
        "jacket",
        "jail",
        "kangaroo",
        "key",
        "keyboard",
        "knee",
        "ladder",
        "lantern",
        "laptop",
        "leaf",
        "leg",
        "light_bulb",
        "lighthouse",
        "lightning",
        "line",
        "lion",
        "lipstick",
        "lobster",
        "lollipop",
        "mailbox",
        "map",
        "marker",
        "matches",
        "megaphone",
        "mermaid",
        "microphone",
        "microwave",
        "monkey",
        "moon",
        "mosquito",
        "motorbike",
        "mountain",
        "mouse",
        "moustache",
        "mouth",
        "mug",
        "mushroom",
        "nail",
        "necklace",
        "nose",
        "ocean",
        "octagon",
        "octopus",
        "onion",
        "oven",
        "owl",
        "paint_can",
        "paintbrush",
        "palm_tree",
        "panda",
        "pants",
        "paper_clip",
        "parachute",
        "parrot",
        "passport",
        "peanut",
        "pear",
        "peas",
        "pencil",
        "penguin",
        "piano",
        "pickup_truck",
        "picture_frame",
        "pig",
        "pillow",
        "pineapple",
        "pizza",
        "pliers",
        "police_car",
        "pond",
        "pool",
        "popsicle",
        "postcard",
        "potato",
        "power_outlet",
        "purse",
        "rabbit",
        "raccoon",
        "radio",
        "rain",
        "rainbow",
        "rake",
        "remote_control",
        "rhinoceros",
        "river",
        "roller_coaster",
        "rollerskates",
        "sailboat",
        "sandwich",
        "saw",
        "saxophone",
        "school_bus",
        "scissors",
        "scorpion",
        "screwdriver",
        "sea_turtle",
        "see_saw",
        "shark",
        "sheep",
        "shoe",
        "shorts",
        "shovel",
        "sink",
        "skateboard",
        "skull",
        "skyscraper",
        "sleeping_bag",
        "smiley_face",
        "snail",
        "snake",
        "snorkel",
        "snowflake",
        "snowman",
        "soccer_ball",
        "sock",
        "speedboat",
        "spider",
        "spoon",
        "spreadsheet",
        "square",
        "squiggle",
        "squirrel",
        "stairs",
        "star",
        "steak",
        "stereo",
        "stethoscope",
        "stitches",
        "stop_sign",
        "stove",
        "strawberry",
        "streetlight",
        "string_bean",
        "submarine",
        "suitcase",
        "sun",
        "swan",
        "sweater",
        "swing_set",
        "sword",
        "t-shirt",
        "table",
        "teapot",
        "teddy-bear",
        "telephone",
        "television",
        "tennis_racquet",
        "tent",
        "tiger",
        "toaster",
        "toe",
        "toilet",
        "tooth",
        "toothbrush",
        "toothpaste",
        "tornado",
        "tractor",
        "traffic_light",
        "train",
        "tree",
        "triangle",
        "trombone",
        "truck",
        "trumpet",
        "umbrella",
        "underwear",
        "van",
        "vase",
        "violin",
        "washing_machine",
        "watermelon",
        "waterslide",
        "whale",
        "wheel",
        "windmill",
        "wine_bottle",
        "wine_glass",
        "wristwatch",
        "yoga",
        "zebra",
        "zigzag",
    ]
    return classes

def class_return_esp():
    classes = [
        "Torre Eiffel",
        "La gran Muralla China",
        "La Mona Lisa",
        "Avion",
        "Reloj",
        "Ambulancia",
        "Angel",
        "Migracion Animal",
        "Hormiga",
        "Yunque",
        "Manzana",
        "Brazo",
        "Esparrago",
        "Hacha",
        "Mochila",
        "Banana",
        "Curita",
        "Granero",
        "Pelota de Baseball",
        "Bate de Baseball",
        "Canasto",
        "Pelota de basket",
        "Vampiro",
        "Bañera",
        "Playa",
        "Oso",
        "Barba",
        "Cama",
        "Abeja",
        "Cinturon",
        "Banco",
        "Bicicleta",
        "Binoculares",
        "Pajaro",
        "Torta de Cumpleaños",
        "Celular",
        "Arandanos",
        "Libro",
        "Bumerang",
        "Tapa de Botella",
        "Corbata Moñito",
        "Pulsera",
        "Cerebro",
        "Pan",
        "Puente",
        "Brocoli",
        "Escoba",
        "Balde",
        "Excavadora",
        "Omnibus",
        "Arbusto",
        "Mariposa",
        "Cactus",
        "Torta",
        "Calculadora",
        "Calendario",
        "Camello",
        "Camara",
        "Camuflaje",
        "Hoguera",
        "Vela",
        "Cañon",
        "Canoa",
        "Auto",
        "Zanahoria",
        "Castillo",
        "Gato",
        "Ventilador de Techo",
        "Telefono Celular",
        "Violonchelo",
        "Silla",
        "Candelabro",
        "Iglesia",
        "Circulo",
        "Clarinete",
        "Reloj",
        "Nube",
        "Taza de Cafe",
        "Brujula",
        "Cumputadora",
        "Galleta",
        "Conservadora",
        "Sofa",
        "Vaca",
        "Cangrejo",
        "Crayon",
        "Cocodrilo",
        "Corona",
        "Crucero",
        "Copa",
        "Diamante",
        "Lavavajillas",
        "Trampolin",
        "Perro",
        "Delfin",
        "Dona",
        "Puerta",
        "Dragon",
        "Comoda-Cajonera",
        "Taladro",
        "Bateria",
        "Pato",
        "Pesas",
        "Oreja",
        "Codo",
        "Elefante",
        "Sobre",
        "Borrador",
        "Ojo",
        "Anteojos",
        "Cara",
        "Ventilador",
        "Pluma",
        "Cerca de Madera",
        "Dedo",
        "Boca de Incendios",
        "Chimenea",
        "Camion de Bomberos",
        "Pescado",
        "Flamenco",
        "Linterna",
        "Ojotas",
        "Lampara de Pie",
        "Flor",
        "Ovni",
        "Pie",
        "Tenedor",
        "Rana",
        "Sarten",
        "Jardin",
        "Manguera",
        "Jirafa",
        "Barba Chivita",
        "Palos de Golf",
        "Uvas",
        "Pasto",
        "Guitarra",
        "Hambuerguesa",
        "Martillo",
        "Mano",
        "Arpa",
        "Sombrero",
        "Auriculares",
        "Erizo",
        "Helicoptero",
        "Casco",
        "Hexagono",
        "Bocha de Hockey",
        "Palo de Hockey",
        "Caballo",
        "Hospital",
        "Globo Aerostatico",
        "Pancho",
        "Jacuzzi",
        "Reloj de Arena",
        "Casa",
        "Planta de Maceta ",
        "Huracan",
        "Helado",
        "Campera",
        "Calabozo",
        "Canguro",
        "Llave",
        "Teclado",
        "Rodilla",
        "Escalera",
        "Linterna",
        "Laptop",
        "Hoja de Arbol",
        "Pierna",
        "Foco",
        "Faro",
        "Rayo",
        "Linea",
        "Leon",
        "Lapiz de Labios",
        "Langosta",
        "Chupetin",
        "Buzon de Cartas",
        "Mapa",
        "Resaltador",
        "matches",
        "Megafono",
        "Sirena",
        "Microfono",
        "Microondas",
        "Mono",
        "Luna",
        "Mosquito",
        "Moto",
        "Montaña",
        "Raton",
        "Bigote",
        "Boca",
        "Taza",
        "Hongo",
        "Clavo",
        "Collar",
        "Nariz",
        "Oceano",
        "Octagono",
        "Pulpo",
        "Cebolla",
        "Horno",
        "Buho",
        "Lata de Pintura",
        "Pincel-Brocha",
        "Palmera",
        "Panda",
        "Pantalones",
        "Clip de Papel",
        "Paracaidas",
        "Loro",
        "Pasaporte",
        "Vaina de Mani",
        "Pera",
        "Arvejas",
        "Lapiz",
        "Pinguino",
        "Piano",
        "Camioneta",
        "Marco de un Cuadro",
        "Cerdo",
        "Almohada",
        "Anana",
        "Pizza",
        "Alicates",
        "Patrulla de Policia",
        "Estanque",
        "Pileta",
        "Paleta de Helado",
        "Tarjeta Postal",
        "Papa",
        "Tomacorriente",
        "Cartera",
        "Conejo",
        "Mapache",
        "Radio",
        "Lluvia",
        "Arcoiris",
        "Rastrillo",
        "Control Remoto",
        "Rinoceronte",
        "Rio",
        "Montaña Rusa",
        "Patines",
        "Velero",
        "Sandwich",
        "Serrucho",
        "Saxofon",
        "Transporte Escolar",
        "Tijeras",
        "Escorpion",
        "Destonillador",
        "Tortuna Marina",
        "Subibaja",
        "Tiburon",
        "Oveja",
        "Zapato",
        "Shorts",
        "Pala",
        "Pileta de Lavar",
        "Patineta",
        "Calavera",
        "Rascacielos",
        "Bolsa de Dormir",
        "Cara Feliz",
        "Caracol",
        "Serpiente",
        "Snorkel",
        "Copo de Nieve",
        "Muñeco de Nieve",
        "Pelota de Futbol",
        "Media",
        "Lancha",
        "Araña",
        "Cuchara",
        "Hoja de Calculo",
        "Cuadrado",
        "Garabato",
        "Ardilla",
        "Escaleras",
        "Estrella",
        "Bife de Carne",
        "Parlantes",
        "Estetoscopio",
        "Puntadas-Cicatriz",
        "Señal de STOP",
        "Cocina",
        "Frutilla",
        "Culumna de Luz",
        "Chaucha",
        "Submarino",
        "Balija",
        "Sol",
        "Cisne",
        "Sweater",
        "Amacas",
        "Espada",
        "Remera",
        "Mesa",
        "Tetera",
        "Oso de Peluche",
        "Telefono Antiguo",
        "Televisor",
        "Raqueta de Tenis",
        "Carpa",
        "Tigre",
        "Tostadora",
        "Dedo",
        "Inodoro",
        "Diente",
        "Cepillo de Dientes",
        "Pasta de Dientes",
        "Tornado",
        "Tractor",
        "Semaforo",
        "Tren",
        "Arbol",
        "Triangulo",
        "Trombom",
        "Camion",
        "Trompeta",
        "Paraguas",
        "Prenda Interior",
        "Camioneta Van",
        "Florero",
        "Violin",
        "Lavarropas",
        "Sandia",
        "Tobogan",
        "Ballena",
        "Rueda",
        "Molino de Viento",
        "Botella de Vino",
        "Copa de Vino",
        "Reloj Pulsera",
        "Yoga",
        "Cebra",
        "Zig Zag",
    ]
    return classes

def class_return_esp_faciles():
    classes = [
        "Torre Eiffel",
        "La gran Muralla China",
        "Avion",
        "Reloj",
        "Ambulancia",
        "Angel",
        "Hormiga",
        "Manzana",
        "Esparrago",
        "Hacha",
        "Mochila",
        "Curita",
        "Pelota de basket",
        "Cama",
        "Banco",
        "Binoculares",
        "Celular",
        "Libro",
        "Corbata Moñito",
        "Puente",
        "Excavadora",
        "Omnibus",
        "Mariposa",
        "Camara",
        "Vela",
        "Auto",
        "Castillo",
        "Violonchelo",
        "Silla",
        "Iglesia",
        "Reloj",
        "Brujula",
        "Cumputadora",
        "Corona",
        "Copa",
        "Diamante",
        "Puerta",
        "Bateria",
        "Sobre",
        "Ojo",
        "Anteojos",
        "Cara",
        "Cerca de Madera",
        "Pescado",
        "Tenedor",
        "Martillo",
        "Mano",
        "Sombrero",
        "Hospital",
        "Reloj de Arena",
        "Casa",
        "Llave",
        "Escalera",
        "Laptop",
        "Foco",
        "Microfono",
        "Pantalones",
        "Clip de Papel",
        "Serrucho",
        "Tijeras",
        "Araña",
        "Remera",
        "Pasta de Dientes",
        "Semaforo",
        "Arbol",
        "Paraguas",
        "Botella de Vino",
    ]
    return classes